basic.forever(function () {
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 5)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 2)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 2)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 5)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 2)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 2)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 5)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 2)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 2)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 5)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 2)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 2)
})
